<?php

namespace App\Services;

use App\Models\Generation;
use App\Models\GenerationFile;

/**
 * Scaffold Generator Service
 *
 * Generates deterministic boilerplate/scaffold files for JS framework projects.
 * These files do NOT require LLM — they are pure templates generated from blueprint config.
 *
 * Scaffold includes:
 * - package.json (with correct dependencies)
 * - Build tool config (vite.config.ts, tsconfig.json)
 * - Entry point (main.tsx/main.ts/app.html)
 * - Router configuration
 * - Layout components (MainLayout)
 * - Global CSS
 * - index.html
 *
 * Only page components are generated by the LLM — scaffold is deterministic.
 */
class ScaffoldGeneratorService
{
    /**
     * Generate scaffold files for a framework project and store them as GenerationFile records.
     *
     * @param  Generation  $generation  The generation record
     * @param  string  $outputFormat  The output format (react, vue, svelte, angular)
     * @param  array  $frameworkConfig  Framework configuration (language, styling, router, stateManagement, buildTool)
     * @param  array  $pages  List of page names to include in routing
     * @param  array  $theme  Theme configuration (primary, secondary, mode)
     * @param  array  $layout  Layout configuration (navigation, footer, etc.)
     * @param  array  $projectInfo  Project information (blogName, companyName, appName, etc.)
     * @return array<GenerationFile> Created scaffold file records
     */
    public function generateScaffold(
        Generation $generation,
        string $outputFormat,
        array $frameworkConfig,
        array $pages,
        array $theme,
        array $layout,
        array $projectInfo = []
    ): array {
        $brandName = $this->getBrandName($projectInfo);

        $files = match ($outputFormat) {
            'react' => $this->generateReactScaffold($frameworkConfig, $pages, $theme, $layout, $brandName),
            'vue' => $this->generateVueScaffold($frameworkConfig, $pages, $theme, $layout, $brandName),
            'svelte' => $this->generateSvelteScaffold($frameworkConfig, $pages, $theme, $layout, $brandName),
            'angular' => $this->generateAngularScaffold($frameworkConfig, $pages, $theme, $layout, $brandName),
            default => [], // HTML+CSS = no scaffold needed
        };

        $records = [];
        foreach ($files as $filePath => $content) {
            $records[] = GenerationFile::create([
                'generation_id' => $generation->id,
                'page_generation_id' => null,
                'file_path' => $filePath,
                'file_content' => $content,
                'file_type' => $this->getFileType($filePath),
                'is_scaffold' => true,
            ]);
        }

        return $records;
    }

    /**
     * Check if the output format requires scaffold generation.
     */
    public function requiresScaffold(string $outputFormat): bool
    {
        return in_array($outputFormat, ['react', 'vue', 'svelte', 'angular']);
    }

    /**
     * Get the file extension for a page component based on output format.
     */
    public function getPageFileExtension(string $outputFormat, array $frameworkConfig): string
    {
        $isTs = ($frameworkConfig['language'] ?? 'typescript') === 'typescript';

        return match ($outputFormat) {
            'react' => $isTs ? 'tsx' : 'jsx',
            'vue' => 'vue',
            'svelte' => 'svelte',
            'angular' => 'component.ts',
            default => 'html',
        };
    }

    /**
     * Get the page file path for a given page name.
     */
    public function getPageFilePath(string $pageName, string $outputFormat, array $frameworkConfig): string
    {
        $componentName = $this->toComponentName($pageName);
        $ext = $this->getPageFileExtension($outputFormat, $frameworkConfig);

        return match ($outputFormat) {
            'react' => "src/pages/{$componentName}.{$ext}",
            'vue' => "src/pages/{$componentName}.{$ext}",
            'svelte' => 'src/routes/'.$this->toKebabCase($pageName)."/+page.{$ext}",
            'angular' => 'src/app/pages/'.$this->toKebabCase($pageName).'/'.$this->toKebabCase($pageName).".{$ext}",
            default => "{$componentName}.html",
        };
    }

    // ========================================================================
    // React Scaffold
    // ========================================================================

    private function generateReactScaffold(array $config, array $pages, array $theme, array $layout, string $brandName = 'Template'): array
    {
        $isTs = ($config['language'] ?? 'typescript') === 'typescript';
        $styling = $config['styling'] ?? 'tailwind';
        $stateManagement = $config['stateManagement'] ?? 'none';
        $hasRouter = $config['router'] ?? true;

        $files = [];

        // package.json
        $files['package.json'] = $this->generateReactPackageJson($config, $stateManagement);

        // vite.config
        $files['vite.config.'.($isTs ? 'ts' : 'js')] = $this->generateReactViteConfig($isTs);

        if ($isTs) {
            $files['tsconfig.json'] = $this->generateReactTsConfig();
        }

        // index.html
        $files['index.html'] = $this->generateIndexHtml('React App', $styling, 'root', '/src/main.tsx');

        // Main entry
        $ext = $isTs ? 'tsx' : 'jsx';
        $files["src/main.{$ext}"] = $this->generateReactMain($isTs);

        // App component
        $files["src/App.{$ext}"] = $this->generateReactApp($pages, $hasRouter, $isTs, $layout);

        // Router
        if ($hasRouter) {
            $files["src/router.{$ext}"] = $this->generateReactRouter($pages, $isTs);
        }

        // Layout
        $files["src/layouts/MainLayout.{$ext}"] = $this->generateReactLayout($pages, $layout, $theme, $isTs, $brandName);

        // Placeholder stub pages — prevent Vite dep-scan ENOENT errors while
        // LLM generates real page content one-by-one.
        foreach ($pages as $page) {
            $componentName = $this->toComponentName($page);
            $filePath = "src/pages/{$componentName}.{$ext}";
            $files[$filePath] = $this->generateReactPlaceholderPage($componentName);
        }

        // Global CSS
        $files['src/styles/globals.css'] = $this->generateGlobalCss($styling, $theme);

        if ($styling === 'tailwind') {
            $files['tailwind.config.js'] = $this->generateTailwindConfig($isTs);
            $files['postcss.config.js'] = $this->generatePostcssConfig();
        }

        return $files;
    }

    private function generateReactPackageJson(array $config, string $stateManagement): string
    {
        $deps = [
            'react' => '^19.0.0',
            'react-dom' => '^19.0.0',
        ];

        if ($config['router'] ?? true) {
            $deps['react-router-dom'] = '^7.1.0';
        }

        if ($stateManagement === 'zustand') {
            $deps['zustand'] = '^5.0.0';
        } elseif ($stateManagement === 'redux') {
            $deps['@reduxjs/toolkit'] = '^2.5.0';
            $deps['react-redux'] = '^9.2.0';
        }

        $devDeps = [
            'vite' => '^6.0.0',
            '@vitejs/plugin-react' => '^4.4.0',
        ];

        if (($config['language'] ?? 'typescript') === 'typescript') {
            $devDeps['typescript'] = '^5.7.0';
            $devDeps['@types/react'] = '^19.0.0';
            $devDeps['@types/react-dom'] = '^19.0.0';
        }

        $styling = $config['styling'] ?? 'tailwind';
        if ($styling === 'tailwind') {
            $devDeps['tailwindcss'] = '^3.4.0';
            $devDeps['postcss'] = '^8.4.0';
            $devDeps['autoprefixer'] = '^10.4.0';
        } elseif ($styling === 'bootstrap') {
            $deps['bootstrap'] = '^5.3.3';
            $deps['@popperjs/core'] = '^2.11.8';
        } elseif ($styling === 'styled-components') {
            $deps['styled-components'] = '^6.1.0';
        }

        $json = [
            'name' => 'generated-template',
            'private' => true,
            'version' => '1.0.0',
            'type' => 'module',
            'scripts' => [
                'dev' => 'vite',
                'build' => 'vite build',
                'preview' => 'vite preview',
            ],
            'dependencies' => $deps,
            'devDependencies' => $devDeps,
        ];

        return json_encode($json, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
    }

    private function generateReactViteConfig(bool $isTs): string
    {
        $ext = $isTs ? 'ts' : 'js';

        return <<<'VITE'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

const previewBase = process.env.VITE_PREVIEW_BASE

export default defineConfig({
  base: previewBase || '/',
  plugins: [react()],
  server: {
    port: 3000,
    host: '0.0.0.0',
    hmr: previewBase ? false : undefined,
  },
})
VITE;
    }

    private function generateReactTsConfig(): string
    {
        $config = [
            'compilerOptions' => [
                'target' => 'ES2020',
                'useDefineForClassFields' => true,
                'lib' => ['ES2020', 'DOM', 'DOM.Iterable'],
                'module' => 'ESNext',
                'skipLibCheck' => true,
                'moduleResolution' => 'bundler',
                'allowImportingTsExtensions' => true,
                'isolatedModules' => true,
                'moduleDetection' => 'force',
                'noEmit' => true,
                'jsx' => 'react-jsx',
                'strict' => true,
                'noUnusedLocals' => true,
                'noUnusedParameters' => true,
                'noFallthroughCasesInSwitch' => true,
                'baseUrl' => '.',
                'paths' => [
                    '@/*' => ['src/*'],
                ],
            ],
            'include' => ['src'],
        ];

        return json_encode($config, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
    }

    private function generateReactMain(bool $isTs): string
    {
        return <<<'MAIN'
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import './styles/globals.css'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
MAIN;
    }

    private function generateReactApp(array $pages, bool $hasRouter, bool $isTs, array $layout): string
    {
        if ($hasRouter) {
            $imports = "import { BrowserRouter } from 'react-router-dom'\nimport AppRouter from './router'";
            $content = "<BrowserRouter basename={import.meta.env.BASE_URL}>\n      <AppRouter />\n    </BrowserRouter>";
        } else {
            $imports = '// No router configured';
            $content = '<div>App Content</div>';
        }

        return <<<APP
{$imports}

export default function App() {
  return (
    {$content}
  )
}
APP;
    }

    private function generateReactRouter(array $pages, bool $isTs): string
    {
        $ext = $isTs ? 'tsx' : 'jsx';
        $imports = [];
        $routes = [];

        foreach ($pages as $page) {
            $componentName = $this->toComponentName($page);
            $routePath = $this->toRoutePath($page);
            $imports[] = "import {$componentName} from './pages/{$componentName}'";
            $routes[] = "      <Route path=\"{$routePath}\" element={<MainLayout><{$componentName} /></MainLayout>} />";
        }

        $importsStr = implode("\n", $imports);
        $routesStr = implode("\n", $routes);

        // Determine default redirect
        $defaultPage = in_array('dashboard', $pages) ? '/dashboard' : '/'.$this->toRoutePath($pages[0] ?? 'dashboard');

        return <<<ROUTER
import { Routes, Route, Navigate } from 'react-router-dom'
import MainLayout from './layouts/MainLayout'
{$importsStr}

export default function AppRouter() {
  return (
    <Routes>
{$routesStr}
      <Route path="*" element={<Navigate to="{$defaultPage}" replace />} />
    </Routes>
  )
}
ROUTER;
    }

    private function generateReactLayout(array $pages, array $layout, array $theme, bool $isTs, string $brandName = 'Template'): string
    {
        $navigation = $layout['navigation'] ?? 'sidebar';
        $navItems = $this->generateNavItems($pages);

        if ($navigation === 'sidebar' || $navigation === 'hybrid') {
            return $this->generateReactSidebarLayout($navItems, $theme, $isTs, $brandName);
        }

        return $this->generateReactTopbarLayout($navItems, $theme, $isTs, $brandName);
    }

    private function generateReactSidebarLayout(string $navItems, array $theme, bool $isTs, string $brandName = 'Template'): string
    {
        $primary = $theme['primary'] ?? '#3B82F6';
        $brandNameJs = addslashes($brandName);

        return <<<LAYOUT
import { useState } from 'react'
import { Link, useLocation } from 'react-router-dom'

interface MainLayoutProps {
  children: React.ReactNode
}

export default function MainLayout({ children }: MainLayoutProps) {
  const [sidebarOpen, setSidebarOpen] = useState(true)
  const location = useLocation()

  const navItems = [
{$navItems}
  ]

  return (
    <div className="flex h-screen bg-gray-100 dark:bg-gray-900">
      {/* Sidebar */}
      <aside
        className={\`\${sidebarOpen ? 'w-64' : 'w-16'} transition-all duration-300 bg-white dark:bg-gray-800 border-r border-gray-200 dark:border-gray-700 flex flex-col\`}
      >
        <div className="h-16 flex items-center justify-between px-4 border-b border-gray-200 dark:border-gray-700">
          {sidebarOpen && <span className="text-xl font-bold text-primary dark:text-white">{$brandNameJs}</span>}
          <button
            onClick={() => setSidebarOpen(!sidebarOpen)}
            className="p-2 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700"
          >
            <svg className="w-5 h-5 text-gray-600 dark:text-gray-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
            </svg>
          </button>
        </div>
        <nav className="flex-1 p-4 space-y-2">
          {navItems.map((item) => (
            <Link
              key={item.path}
              to={item.path}
              className={\`flex items-center gap-3 px-3 py-2 rounded-lg transition-colors \${
                location.pathname === item.path
                  ? 'bg-primary/10 text-primary dark:bg-primary/20 dark:text-primary'
                  : 'text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700'
              }\`}
            >
              <span className="text-sm font-medium">{sidebarOpen ? item.label : item.label[0]}</span>
            </Link>
          ))}
        </nav>
      </aside>

      {/* Main Content */}
      <div className="flex-1 flex flex-col overflow-hidden">
        <header className="h-16 bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 flex items-center px-6">
          <h1 className="text-lg font-semibold text-gray-900 dark:text-white">
            {navItems.find(i => i.path === location.pathname)?.label ?? 'Page'}
          </h1>
        </header>
        <main className="flex-1 overflow-auto p-6">
          {children}
        </main>
      </div>
    </div>
  )
}
LAYOUT;
    }

    private function generateReactTopbarLayout(string $navItems, array $theme, bool $isTs, string $brandName = 'Template'): string
    {
        $brandNameJs = addslashes($brandName);

        return <<<LAYOUT
import { Link, useLocation } from 'react-router-dom'

interface MainLayoutProps {
  children: React.ReactNode
}

export default function MainLayout({ children }: MainLayoutProps) {
  const location = useLocation()

  const navItems = [
{$navItems}
  ]

  return (
    <div className="min-h-screen bg-gray-100 dark:bg-gray-900">
      <header className="bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <span className="text-xl font-bold text-primary dark:text-white">{$brandNameJs}</span>
            <nav className="flex gap-4">
              {navItems.map((item) => (
                <Link
                  key={item.path}
                  to={item.path}
                  className={\`px-3 py-2 rounded-lg text-sm font-medium transition-colors \${
                    location.pathname === item.path
                      ? 'bg-primary/10 text-primary dark:bg-primary/20 dark:text-primary'
                      : 'text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700'
                  }\`}
                >
                  {item.label}
                </Link>
              ))}
            </nav>
          </div>
        </div>
      </header>
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {children}
      </main>
    </div>
  )
}
LAYOUT;
    }

    /**
     * Generate a placeholder React page component.
     * Will be overwritten when the LLM generates the actual page.
     */
    private function generateReactPlaceholderPage(string $componentName): string
    {
        return <<<PAGE
export default function {$componentName}() {
  return (
    <div className="flex items-center justify-center min-h-[60vh]">
      <div className="text-center">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-500 mx-auto mb-4"></div>
        <p className="text-gray-500 dark:text-gray-400">Generating {$componentName}...</p>
      </div>
    </div>
  )
}
PAGE;
    }

    // ========================================================================
    // Vue Scaffold
    // ========================================================================

    private function generateVueScaffold(array $config, array $pages, array $theme, array $layout, string $brandName = 'Template'): array
    {
        $isTs = ($config['language'] ?? 'typescript') === 'typescript';
        $styling = $config['styling'] ?? 'tailwind';
        $stateManagement = $config['stateManagement'] ?? 'none';
        $hasRouter = $config['router'] ?? true;

        $files = [];

        $files['package.json'] = $this->generateVuePackageJson($config, $stateManagement);
        $files['vite.config.'.($isTs ? 'ts' : 'js')] = $this->generateVueViteConfig($isTs);

        if ($isTs) {
            $files['tsconfig.json'] = $this->generateVueTsConfig();
        }

        $files['index.html'] = $this->generateIndexHtml('Vue App', $styling, 'app', '/src/main.ts');

        $ext = $isTs ? 'ts' : 'js';
        $files["src/main.{$ext}"] = $this->generateVueMain($hasRouter, $stateManagement, $isTs);
        $files['src/App.vue'] = $this->generateVueApp($hasRouter);

        if ($hasRouter) {
            $files["src/router/index.{$ext}"] = $this->generateVueRouter($pages, $isTs);
        }

        $files['src/layouts/MainLayout.vue'] = $this->generateVueLayout($pages, $layout, $theme, $brandName);

        // Placeholder stub pages — prevent Vite dep-scan ENOENT errors while
        // LLM generates real page content one-by-one.
        foreach ($pages as $page) {
            $componentName = $this->toComponentName($page);
            $filePath = "src/pages/{$componentName}.vue";
            $files[$filePath] = $this->generateVuePlaceholderPage($componentName);
        }

        $files['src/assets/main.css'] = $this->generateGlobalCss($styling, $theme);

        if ($styling === 'tailwind') {
            $files['tailwind.config.js'] = $this->generateTailwindConfig($isTs);
            $files['postcss.config.js'] = $this->generatePostcssConfig();
        }

        return $files;
    }

    private function generateVuePackageJson(array $config, string $stateManagement): string
    {
        $deps = [
            'vue' => '^3.5.0',
        ];

        if ($config['router'] ?? true) {
            $deps['vue-router'] = '^4.5.0';
        }

        if ($stateManagement === 'pinia') {
            $deps['pinia'] = '^2.3.0';
        }

        $devDeps = [
            'vite' => '^6.0.0',
            '@vitejs/plugin-vue' => '^5.2.0',
        ];

        if (($config['language'] ?? 'typescript') === 'typescript') {
            $devDeps['typescript'] = '^5.7.0';
            $devDeps['vue-tsc'] = '^2.2.0';
        }

        $styling = $config['styling'] ?? 'tailwind';
        if ($styling === 'tailwind') {
            $devDeps['tailwindcss'] = '^3.4.0';
            $devDeps['postcss'] = '^8.4.0';
            $devDeps['autoprefixer'] = '^10.4.0';
        } elseif ($styling === 'bootstrap') {
            $deps['bootstrap'] = '^5.3.3';
            $deps['@popperjs/core'] = '^2.11.8';
        }

        $json = [
            'name' => 'generated-template',
            'private' => true,
            'version' => '1.0.0',
            'type' => 'module',
            'scripts' => [
                'dev' => 'vite',
                'build' => 'vue-tsc && vite build',
                'preview' => 'vite preview',
            ],
            'dependencies' => $deps,
            'devDependencies' => $devDeps,
        ];

        return json_encode($json, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
    }

    private function generateVueViteConfig(bool $isTs): string
    {
        return <<<'VITE'
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import { resolve } from 'path'

const previewBase = process.env.VITE_PREVIEW_BASE

export default defineConfig({
  base: previewBase || '/',
  plugins: [vue()],
  resolve: {
    alias: {
      '@': resolve(__dirname, 'src'),
    },
  },
  server: {
    port: 3000,
    host: '0.0.0.0',
    hmr: previewBase ? false : undefined,
  },
})
VITE;
    }

    private function generateVueTsConfig(): string
    {
        $config = [
            'compilerOptions' => [
                'target' => 'ES2020',
                'useDefineForClassFields' => true,
                'module' => 'ESNext',
                'lib' => ['ES2020', 'DOM', 'DOM.Iterable'],
                'skipLibCheck' => true,
                'moduleResolution' => 'bundler',
                'allowImportingTsExtensions' => true,
                'isolatedModules' => true,
                'moduleDetection' => 'force',
                'noEmit' => true,
                'jsx' => 'preserve',
                'strict' => true,
                'noUnusedLocals' => true,
                'noUnusedParameters' => true,
                'noFallthroughCasesInSwitch' => true,
                'baseUrl' => '.',
                'paths' => [
                    '@/*' => ['src/*'],
                ],
            ],
            'include' => ['src/**/*.ts', 'src/**/*.d.ts', 'src/**/*.vue'],
        ];

        return json_encode($config, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
    }

    private function generateVueMain(bool $hasRouter, string $stateManagement, bool $isTs): string
    {
        $imports = ["import { createApp } from 'vue'", "import App from './App.vue'"];
        $uses = [];

        if ($hasRouter) {
            $imports[] = "import router from './router'";
            $uses[] = 'app.use(router)';
        }

        if ($stateManagement === 'pinia') {
            $imports[] = "import { createPinia } from 'pinia'";
            $uses[] = 'app.use(createPinia())';
        }

        $imports[] = "import './assets/main.css'";

        $importsStr = implode("\n", $imports);
        $usesStr = implode("\n", $uses);

        return <<<MAIN
{$importsStr}

const app = createApp(App)
{$usesStr}
app.mount('#app')
MAIN;
    }

    private function generateVueApp(bool $hasRouter): string
    {
        $content = $hasRouter ? '<RouterView />' : '<div>App Content</div>';
        $imports = $hasRouter ? "import { RouterView } from 'vue-router'" : '';

        return <<<APP
<script setup lang="ts">
{$imports}
</script>

<template>
  {$content}
</template>
APP;
    }

    private function generateVueRouter(array $pages, bool $isTs): string
    {
        $imports = [];
        $routes = [];

        foreach ($pages as $page) {
            $componentName = $this->toComponentName($page);
            $routePath = $this->toRoutePath($page);
            $routes[] = "    {\n      path: '{$routePath}',\n      name: '{$routePath}',\n      component: () => import('@/pages/{$componentName}.vue'),\n      meta: { layout: 'main' },\n    },";
        }

        $routesStr = implode("\n", $routes);
        $defaultPage = in_array('dashboard', $pages) ? '/dashboard' : '/'.$this->toRoutePath($pages[0] ?? 'dashboard');

        return <<<ROUTER
import { createRouter, createWebHistory } from 'vue-router'
import MainLayout from '@/layouts/MainLayout.vue'

const router = createRouter({
  history: createWebHistory(import.meta.env.BASE_URL),
  routes: [
    {
      path: '/',
      component: MainLayout,
      children: [
{$routesStr}
      ],
    },
    {
      path: '/:pathMatch(.*)*',
      redirect: '{$defaultPage}',
    },
  ],
})

export default router
ROUTER;
    }

    private function generateVueLayout(array $pages, array $layout, array $theme, string $brandName = 'Template'): string
    {
        $navigation = $layout['navigation'] ?? 'sidebar';
        $navItemsArray = $this->generateVueNavItems($pages);

        if ($navigation === 'sidebar' || $navigation === 'hybrid') {
            return $this->generateVueSidebarLayout($navItemsArray, $theme, $brandName);
        }

        return $this->generateVueTopbarLayout($navItemsArray, $theme, $brandName);
    }

    private function generateVueSidebarLayout(string $navItems, array $theme, string $brandName = 'Template'): string
    {
        $escapedBrand = htmlspecialchars($brandName, ENT_QUOTES, 'UTF-8');

        return <<<'LAYOUT'
<script setup lang="ts">
import { ref } from 'vue'
import { RouterLink, RouterView, useRoute } from 'vue-router'

const sidebarOpen = ref(true)
const route = useRoute()

const navItems = [
LAYOUT."\n{$navItems}".<<<'LAYOUT'

]
</script>

<template>
  <div class="flex h-screen bg-gray-100 dark:bg-gray-900">
    <!-- Sidebar -->
    <aside
      :class="[sidebarOpen ? 'w-64' : 'w-16', 'transition-all duration-300 bg-white dark:bg-gray-800 border-r border-gray-200 dark:border-gray-700 flex flex-col']"
    >
      <div class="h-16 flex items-center justify-between px-4 border-b border-gray-200 dark:border-gray-700">
LAYOUT."\n        <span v-if=\"sidebarOpen\" class=\"text-xl font-bold text-primary dark:text-white\">{$escapedBrand}</span>".<<<'LAYOUT'

        <button
          @click="sidebarOpen = !sidebarOpen"
          class="p-2 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700"
        >
          <svg class="w-5 h-5 text-gray-600 dark:text-gray-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
        </button>
      </div>
      <nav class="flex-1 p-4 space-y-2">
        <RouterLink
          v-for="item in navItems"
          :key="item.path"
          :to="item.path"
          :class="[
            'flex items-center gap-3 px-3 py-2 rounded-lg transition-colors',
            route.path === item.path
              ? 'bg-primary/10 text-primary dark:bg-primary/20 dark:text-primary'
              : 'text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700'
          ]"
        >
          <span class="text-sm font-medium">{{ sidebarOpen ? item.label : item.label[0] }}</span>
        </RouterLink>
      </nav>
    </aside>

    <!-- Main Content -->
    <div class="flex-1 flex flex-col overflow-hidden">
      <header class="h-16 bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 flex items-center px-6">
        <h1 class="text-lg font-semibold text-gray-900 dark:text-white">
          {{ navItems.find(i => i.path === route.path)?.label ?? 'Page' }}
        </h1>
      </header>
      <main class="flex-1 overflow-auto p-6">
        <RouterView />
      </main>
    </div>
  </div>
</template>
LAYOUT;
    }

    private function generateVueTopbarLayout(string $navItems, array $theme, string $brandName = 'Template'): string
    {
        $escapedBrand = htmlspecialchars($brandName, ENT_QUOTES, 'UTF-8');

        return <<<'LAYOUT'
<script setup lang="ts">
import { RouterLink, RouterView, useRoute } from 'vue-router'

const route = useRoute()

const navItems = [
LAYOUT."\n{$navItems}".<<<'LAYOUT'

]
</script>

<template>
  <div class="min-h-screen bg-gray-100 dark:bg-gray-900">
    <header class="bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex items-center justify-between h-16">
LAYOUT."\n          <span class=\"text-xl font-bold text-primary dark:text-white\">{$escapedBrand}</span>".<<<'LAYOUT'

          <nav class="flex gap-4">
            <RouterLink
              v-for="item in navItems"
              :key="item.path"
              :to="item.path"
              :class="[
                'px-3 py-2 rounded-lg text-sm font-medium transition-colors',
                route.path === item.path
                  ? 'bg-primary/10 text-primary dark:bg-primary/20 dark:text-primary'
                  : 'text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700'
              ]"
            >
              {{ item.label }}
            </RouterLink>
          </nav>
        </div>
      </div>
    </header>
    <main class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <RouterView />
    </main>
  </div>
</template>
LAYOUT;
    }

    // ========================================================================
    // Svelte Scaffold
    // ========================================================================

    /**
     * Generate a placeholder Vue page component.
     * Will be overwritten when the LLM generates the actual page.
     */
    private function generateVuePlaceholderPage(string $componentName): string
    {
        return <<<PAGE
<script setup lang="ts">
// Placeholder — will be replaced by LLM-generated content
</script>

<template>
  <div class="flex items-center justify-center min-h-[60vh]">
    <div class="text-center">
      <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-500 mx-auto mb-4"></div>
      <p class="text-gray-500 dark:text-gray-400">Generating {$componentName}...</p>
    </div>
  </div>
</template>
PAGE;
    }

    private function generateSvelteScaffold(array $config, array $pages, array $theme, array $layout, string $brandName = 'Template'): array
    {
        $isTs = ($config['language'] ?? 'typescript') === 'typescript';
        $styling = $config['styling'] ?? 'tailwind';

        $files = [];

        $files['package.json'] = $this->generateSveltePackageJson($config);
        $files['svelte.config.js'] = $this->generateSvelteConfig();
        $files['vite.config.'.($isTs ? 'ts' : 'js')] = $this->generateSvelteViteConfig();

        if ($isTs) {
            $files['tsconfig.json'] = $this->generateSvelteTsConfig();
        }

        $files['src/app.html'] = $this->generateSvelteAppHtml($styling);
        $files['src/app.css'] = $this->generateGlobalCss($styling, $theme);
        $files['src/routes/+layout.svelte'] = $this->generateSvelteRootLayout($pages, $layout, $theme);
        $files['src/routes/+page.svelte'] = $this->generateSvelteRedirectPage($pages);

        // Layout component
        $files['src/lib/layouts/MainLayout.svelte'] = $this->generateSvelteLayoutComponent($pages, $layout, $theme, $brandName);

        // Placeholder stub pages — prevent Vite dep-scan ENOENT errors while
        // LLM generates real page content one-by-one.
        foreach ($pages as $page) {
            $kebab = $this->toKebabCase($page);
            $componentName = $this->toComponentName($page);
            $filePath = "src/routes/{$kebab}/+page.svelte";
            $files[$filePath] = $this->generateSveltePlaceholderPage($componentName);
        }

        if ($styling === 'tailwind') {
            $files['tailwind.config.js'] = $this->generateTailwindConfig(false);
            $files['postcss.config.js'] = $this->generatePostcssConfig();
        }

        return $files;
    }

    private function generateSveltePackageJson(array $config): string
    {
        $deps = [];
        $devDeps = [
            'svelte' => '^5.0.0',
            '@sveltejs/kit' => '^2.15.0',
            '@sveltejs/vite-plugin-svelte' => '^4.0.0',
            'vite' => '^6.0.0',
        ];

        if (($config['language'] ?? 'typescript') === 'typescript') {
            $devDeps['typescript'] = '^5.7.0';
            $devDeps['svelte-check'] = '^4.0.0';
        }

        $styling = $config['styling'] ?? 'tailwind';
        if ($styling === 'tailwind') {
            $devDeps['tailwindcss'] = '^3.4.0';
            $devDeps['postcss'] = '^8.4.0';
            $devDeps['autoprefixer'] = '^10.4.0';
        } elseif ($styling === 'bootstrap') {
            $deps['bootstrap'] = '^5.3.3';
            $deps['@popperjs/core'] = '^2.11.8';
        }

        $json = [
            'name' => 'generated-template',
            'private' => true,
            'version' => '1.0.0',
            'type' => 'module',
            'scripts' => [
                'dev' => 'vite dev',
                'build' => 'vite build',
                'preview' => 'vite preview',
            ],
            'dependencies' => empty($deps) ? (object) $deps : $deps,
            'devDependencies' => $devDeps,
        ];

        return json_encode($json, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
    }

    private function generateSvelteConfig(): string
    {
        return <<<'CONFIG'
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte'

export default {
  preprocess: vitePreprocess(),
}
CONFIG;
    }

    private function generateSvelteViteConfig(): string
    {
        return <<<'VITE'
import { defineConfig } from 'vite'
import { sveltekit } from '@sveltejs/kit/vite'

const previewBase = process.env.VITE_PREVIEW_BASE

export default defineConfig({
  base: previewBase || '/',
  plugins: [sveltekit()],
  server: {
    port: 3000,
    host: '0.0.0.0',
    hmr: previewBase ? false : undefined,
  },
})
VITE;
    }

    private function generateSvelteTsConfig(): string
    {
        $config = [
            'extends' => './.svelte-kit/tsconfig.json',
            'compilerOptions' => [
                'strict' => true,
                'noUnusedLocals' => true,
                'noUnusedParameters' => true,
            ],
        ];

        return json_encode($config, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
    }

    private function generateSvelteAppHtml(string $styling): string
    {
        return <<<'HTML'
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Generated Template</title>
    %sveltekit.head%
  </head>
  <body>
    <div>%sveltekit.body%</div>
  </body>
</html>
HTML;
    }

    private function generateSvelteRootLayout(array $pages, array $layout, array $theme): string
    {
        return <<<'LAYOUT'
<script>
  import '../app.css'
  import MainLayout from '$lib/layouts/MainLayout.svelte'

  let { children } = $props()
</script>

<MainLayout>
  {@render children()}
</MainLayout>
LAYOUT;
    }

    private function generateSvelteRedirectPage(array $pages): string
    {
        $defaultPage = in_array('dashboard', $pages) ? 'dashboard' : ($pages[0] ?? 'dashboard');

        return <<<SVELTE
<script>
  import { goto } from '\$app/navigation'
  import { onMount } from 'svelte'

  onMount(() => {
    goto('/{$defaultPage}')
  })
</script>

<p>Redirecting...</p>
SVELTE;
    }

    private function generateSvelteLayoutComponent(array $pages, array $layout, array $theme, string $brandName = 'Template'): string
    {
        $navigation = $layout['navigation'] ?? 'sidebar';
        $escapedBrand = htmlspecialchars($brandName, ENT_QUOTES, 'UTF-8');
        $navItems = "[\n";
        foreach ($pages as $page) {
            $label = $this->toLabel($page);
            $path = '/'.$this->toRoutePath($page);
            $navItems .= "    { label: '{$label}', path: '{$path}' },\n";
        }
        $navItems .= '  ]';

        return <<<LAYOUT
<script>
  import { page } from '\$app/state'

  let { children } = \$props()
  let sidebarOpen = \$state(true)

  const navItems = {$navItems}
</script>

<div class="flex h-screen bg-gray-100 dark:bg-gray-900">
  <aside class="{sidebarOpen ? 'w-64' : 'w-16'} transition-all duration-300 bg-white dark:bg-gray-800 border-r border-gray-200 dark:border-gray-700 flex flex-col">
    <div class="h-16 flex items-center justify-between px-4 border-b border-gray-200 dark:border-gray-700">
      {#if sidebarOpen}
        <span class="text-xl font-bold text-primary dark:text-white">{$escapedBrand}</span>
      {/if}
      <button onclick={() => sidebarOpen = !sidebarOpen} class="p-2 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700">
        <svg class="w-5 h-5 text-gray-600 dark:text-gray-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
        </svg>
      </button>
    </div>
    <nav class="flex-1 p-4 space-y-2">
      {#each navItems as item}
        <a
          href={item.path}
          class="flex items-center gap-3 px-3 py-2 rounded-lg transition-colors {page.url.pathname === item.path ? 'bg-primary/10 text-primary dark:bg-primary/20 dark:text-primary' : 'text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700'}"
        >
          <span class="text-sm font-medium">{sidebarOpen ? item.label : item.label[0]}</span>
        </a>
      {/each}
    </nav>
  </aside>

  <div class="flex-1 flex flex-col overflow-hidden">
    <header class="h-16 bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 flex items-center px-6">
      <h1 class="text-lg font-semibold text-gray-900 dark:text-white">
        {navItems.find(i => i.path === page.url.pathname)?.label ?? 'Page'}
      </h1>
    </header>
    <main class="flex-1 overflow-auto p-6">
      {@render children()}
    </main>
  </div>
</div>
LAYOUT;
    }

    // ========================================================================
    // Angular Scaffold
    // ========================================================================

    /**
     * Generate a placeholder Svelte page component.
     * Will be overwritten when the LLM generates the actual page.
     */
    private function generateSveltePlaceholderPage(string $componentName): string
    {
        return <<<PAGE
<div class="flex items-center justify-center min-h-[60vh]">
  <div class="text-center">
    <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-500 mx-auto mb-4"></div>
    <p class="text-gray-500 dark:text-gray-400">Generating {$componentName}...</p>
  </div>
</div>
PAGE;
    }

    private function generateAngularScaffold(array $config, array $pages, array $theme, array $layout, string $brandName = 'Template'): array
    {
        $styling = $config['styling'] ?? 'tailwind';

        $files = [];

        $files['package.json'] = $this->generateAngularPackageJson($config);
        $files['tsconfig.json'] = $this->generateAngularTsConfig();
        $files['angular.json'] = $this->generateAngularJson();

        $files['src/index.html'] = $this->generateAngularIndexHtml($styling);
        $files['src/main.ts'] = $this->generateAngularMain($pages);
        $files['src/styles.css'] = $this->generateGlobalCss($styling, $theme);
        $files['src/app/app.component.ts'] = $this->generateAngularAppComponent();
        $files['src/app/app.routes.ts'] = $this->generateAngularRoutes($pages);
        $files['src/app/layouts/main-layout.component.ts'] = $this->generateAngularLayout($pages, $layout, $theme, $brandName);

        // Placeholder stub pages — prevent Vite dep-scan ENOENT errors while
        // LLM generates real page content one-by-one.
        foreach ($pages as $page) {
            $componentName = $this->toComponentName($page).'Component';
            $kebab = $this->toKebabCase($page);
            $filePath = "src/app/pages/{$kebab}/{$kebab}.component.ts";
            $files[$filePath] = $this->generateAngularPlaceholderPage($componentName, $kebab);
        }

        return $files;
    }

    /**
     * Generate a placeholder Angular page component.
     * Will be overwritten when the LLM generates the actual page.
     */
    private function generateAngularPlaceholderPage(string $componentName, string $selector): string
    {
        return <<<PAGE
import { Component } from '@angular/core'

@Component({
  selector: 'app-{$selector}',
  standalone: true,
  template: \`
    <div class="flex items-center justify-center min-h-[60vh]">
      <div class="text-center">
        <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-500 mx-auto mb-4"></div>
        <p class="text-gray-500 dark:text-gray-400">Generating...</p>
      </div>
    </div>
  \`,
})
export class {$componentName} {}
PAGE;
    }

    private function generateAngularPackageJson(array $config): string
    {
        $deps = [
            '@angular/core' => '^19.0.0',
            '@angular/common' => '^19.0.0',
            '@angular/compiler' => '^19.0.0',
            '@angular/platform-browser' => '^19.0.0',
            '@angular/platform-browser-dynamic' => '^19.0.0',
            '@angular/router' => '^19.0.0',
            'rxjs' => '^7.8.0',
            'zone.js' => '^0.15.0',
        ];

        if (($config['stateManagement'] ?? 'none') === 'ngrx') {
            $deps['@ngrx/store'] = '^19.0.0';
        }

        $devDeps = [
            '@angular/cli' => '^19.0.0',
            '@angular/compiler-cli' => '^19.0.0',
            'typescript' => '^5.7.0',
        ];

        $styling = $config['styling'] ?? 'tailwind';
        if ($styling === 'tailwind') {
            $devDeps['tailwindcss'] = '^3.4.0';
            $devDeps['postcss'] = '^8.4.0';
            $devDeps['autoprefixer'] = '^10.4.0';
        } elseif ($styling === 'bootstrap') {
            $deps['bootstrap'] = '^5.3.3';
            $deps['@popperjs/core'] = '^2.11.8';
        }

        $json = [
            'name' => 'generated-template',
            'private' => true,
            'version' => '1.0.0',
            'scripts' => [
                'start' => 'ng serve --port 3000 --host 0.0.0.0',
                'build' => 'ng build',
            ],
            'dependencies' => $deps,
            'devDependencies' => $devDeps,
        ];

        return json_encode($json, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
    }

    private function generateAngularTsConfig(): string
    {
        $config = [
            'compilerOptions' => [
                'target' => 'ES2022',
                'module' => 'ES2022',
                'lib' => ['ES2022', 'DOM'],
                'moduleResolution' => 'bundler',
                'strict' => true,
                'skipLibCheck' => true,
                'experimentalDecorators' => true,
                'noEmit' => true,
            ],
            'include' => ['src'],
        ];

        return json_encode($config, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
    }

    private function generateAngularJson(): string
    {
        $config = [
            'projects' => [
                'app' => [
                    'root' => '',
                    'sourceRoot' => 'src',
                    'architect' => [
                        'build' => [
                            'builder' => '@angular/build:application',
                            'options' => [
                                'outputPath' => 'dist',
                                'index' => 'src/index.html',
                                'browser' => 'src/main.ts',
                                'styles' => ['src/styles.css'],
                            ],
                        ],
                        'serve' => [
                            'builder' => '@angular/build:dev-server',
                        ],
                    ],
                ],
            ],
        ];

        return json_encode($config, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
    }

    private function generateAngularIndexHtml(string $styling): string
    {
        return <<<'HTML'
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Generated Template</title>
</head>
<body>
  <app-root></app-root>
</body>
</html>
HTML;
    }

    private function generateAngularMain(array $pages): string
    {
        return <<<'MAIN'
import { bootstrapApplication } from '@angular/platform-browser'
import { provideRouter } from '@angular/router'
import { AppComponent } from './app/app.component'
import { routes } from './app/app.routes'

bootstrapApplication(AppComponent, {
  providers: [
    provideRouter(routes),
  ],
})
MAIN;
    }

    private function generateAngularAppComponent(): string
    {
        return <<<'COMPONENT'
import { Component } from '@angular/core'
import { RouterOutlet } from '@angular/router'

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet],
  template: '<router-outlet></router-outlet>',
})
export class AppComponent {}
COMPONENT;
    }

    private function generateAngularRoutes(array $pages): string
    {
        $imports = ["import { Routes } from '@angular/router'", "import { MainLayoutComponent } from './layouts/main-layout.component'"];
        $routes = [];

        foreach ($pages as $page) {
            $componentName = $this->toComponentName($page).'Component';
            $kebab = $this->toKebabCase($page);
            $routePath = $this->toRoutePath($page);
            $routes[] = "      {\n        path: '{$routePath}',\n        loadComponent: () => import('./pages/{$kebab}/{$kebab}.component').then(m => m.{$componentName}),\n      },";
        }

        $routesStr = implode("\n", $routes);
        $defaultPage = in_array('dashboard', $pages) ? 'dashboard' : $this->toRoutePath($pages[0] ?? 'dashboard');

        return <<<ROUTES
import { Routes } from '@angular/router'
import { MainLayoutComponent } from './layouts/main-layout.component'

export const routes: Routes = [
  {
    path: '',
    component: MainLayoutComponent,
    children: [
{$routesStr}
      { path: '', redirectTo: '{$defaultPage}', pathMatch: 'full' },
    ],
  },
  { path: '**', redirectTo: '{$defaultPage}' },
]
ROUTES;
    }

    private function generateAngularLayout(array $pages, array $layout, array $theme, string $brandName = 'Template'): string
    {
        $escapedBrand = htmlspecialchars($brandName, ENT_QUOTES, 'UTF-8');
        $navItems = [];
        foreach ($pages as $page) {
            $label = $this->toLabel($page);
            $path = '/'.$this->toRoutePath($page);
            $navItems[] = "    { label: '{$label}', path: '{$path}' },";
        }
        $navItemsStr = implode("\n", $navItems);

        return <<<COMPONENT
import { Component } from '@angular/core'
import { RouterOutlet, RouterLink, RouterLinkActive } from '@angular/router'
import { CommonModule } from '@angular/common'

@Component({
  selector: 'app-main-layout',
  standalone: true,
  imports: [CommonModule, RouterOutlet, RouterLink, RouterLinkActive],
  template: \`
    <div class="flex h-screen bg-gray-100 dark:bg-gray-900">
      <aside [class]="sidebarOpen ? 'w-64' : 'w-16'" class="transition-all duration-300 bg-white dark:bg-gray-800 border-r border-gray-200 dark:border-gray-700 flex flex-col">
        <div class="h-16 flex items-center justify-between px-4 border-b border-gray-200 dark:border-gray-700">
          <span *ngIf="sidebarOpen" class="text-xl font-bold text-primary dark:text-white">{$escapedBrand}</span>
          <button (click)="sidebarOpen = !sidebarOpen" class="p-2 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700">
            <svg class="w-5 h-5 text-gray-600 dark:text-gray-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
            </svg>
          </button>
        </div>
        <nav class="flex-1 p-4 space-y-2">
          <a *ngFor="let item of navItems" [routerLink]="item.path" routerLinkActive="bg-primary/10 text-primary dark:bg-primary/20 dark:text-primary" class="flex items-center gap-3 px-3 py-2 rounded-lg transition-colors text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700">
            <span class="text-sm font-medium">{{ sidebarOpen ? item.label : item.label[0] }}</span>
          </a>
        </nav>
      </aside>
      <div class="flex-1 flex flex-col overflow-hidden">
        <header class="h-16 bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 flex items-center px-6">
          <h1 class="text-lg font-semibold text-gray-900 dark:text-white">Page</h1>
        </header>
        <main class="flex-1 overflow-auto p-6">
          <router-outlet></router-outlet>
        </main>
      </div>
    </div>
  \`,
})
export class MainLayoutComponent {
  sidebarOpen = true
  navItems = [
{$navItemsStr}
  ]
}
COMPONENT;
    }

    // ========================================================================
    // Shared Helpers
    // ========================================================================

    private function generateIndexHtml(string $title, string $styling, string $mountId = 'root', string $entryFile = '/src/main.tsx'): string
    {
        $cdnLinks = '';
        if ($styling === 'bootstrap') {
            $cdnLinks = '    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">';
        }

        return <<<HTML
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{$title}</title>
{$cdnLinks}
  </head>
  <body>
    <div id="{$mountId}"></div>
    <script type="module" src="{$entryFile}"></script>
  </body>
</html>
HTML;
    }

    private function generateGlobalCss(string $styling, array $theme): string
    {
        $primary = $theme['primary'] ?? '#3B82F6';
        $secondary = $theme['secondary'] ?? '#6366F1';

        if ($styling === 'tailwind') {
            return <<<CSS
@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --color-primary: {$primary};
  --color-secondary: {$secondary};
}

body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

/* Primary/secondary color utilities with opacity support */
@layer utilities {
  .bg-primary {
    background-color: var(--color-primary);
  }
  .bg-primary\/10 {
    background-color: color-mix(in srgb, var(--color-primary) 10%, transparent);
  }
  .bg-primary\/20 {
    background-color: color-mix(in srgb, var(--color-primary) 20%, transparent);
  }
  .text-primary {
    color: var(--color-primary);
  }
  .border-primary {
    border-color: var(--color-primary);
  }
  .bg-secondary {
    background-color: var(--color-secondary);
  }
  .text-secondary {
    color: var(--color-secondary);
  }
  .border-secondary {
    border-color: var(--color-secondary);
  }
  .ring-primary {
    --tw-ring-color: var(--color-primary);
  }
  .hover\\:bg-primary:hover {
    background-color: var(--color-primary);
  }
  .hover\\:text-primary:hover {
    color: var(--color-primary);
  }
}
CSS;
        }

        if ($styling === 'bootstrap') {
            return <<<CSS
@import "bootstrap/dist/css/bootstrap.min.css";

:root {
  --bs-primary: {$primary};
  --bs-secondary: {$secondary};
  --color-primary: {$primary};
  --color-secondary: {$secondary};
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}
CSS;
        }

        // css-modules, styled-components, or plain CSS
        return <<<CSS
:root {
  --color-primary: {$primary};
  --color-secondary: {$secondary};
}

*, *::before, *::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  background-color: #f3f4f6;
  color: #111827;
}
CSS;
    }

    private function generateTailwindConfig(bool $isTs): string
    {
        return <<<'CONFIG'
/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx,vue,svelte}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: 'var(--color-primary)',
        secondary: 'var(--color-secondary)',
      },
    },
  },
  plugins: [],
}
CONFIG;
    }

    private function generatePostcssConfig(): string
    {
        return <<<'CONFIG'
export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
CONFIG;
    }

    /**
     * Generate navigation items as JS array string (for React)
     */
    private function generateNavItems(array $pages): string
    {
        $items = [];
        foreach ($pages as $page) {
            $label = $this->toLabel($page);
            $path = '/'.$this->toRoutePath($page);
            $items[] = "    { label: '{$label}', path: '{$path}' },";
        }

        return implode("\n", $items);
    }

    /**
     * Generate navigation items for Vue templates
     */
    private function generateVueNavItems(array $pages): string
    {
        return $this->generateNavItems($pages);
    }

    /**
     * Convert page name to PascalCase component name
     * e.g. "user-management" → "UserManagement", "custom:inventory" → "Inventory"
     */
    private function toComponentName(string $page): string
    {
        if (str_starts_with($page, 'custom:')) {
            $page = substr($page, 7);
        }
        if (str_starts_with($page, 'component:custom:')) {
            $page = substr($page, 17);
        }
        if (str_starts_with($page, 'component:')) {
            $page = substr($page, 10);
        }

        return str_replace(' ', '', ucwords(str_replace('-', ' ', $page)));
    }

    /**
     * Convert page name to route path
     * e.g. "user-management" → "user-management", "custom:inventory" → "inventory"
     */
    private function toRoutePath(string $page): string
    {
        if (str_starts_with($page, 'custom:')) {
            $page = substr($page, 7);
        }
        if (str_starts_with($page, 'component:custom:')) {
            $page = substr($page, 17);
        }
        if (str_starts_with($page, 'component:')) {
            $page = substr($page, 10);
        }

        return $this->toKebabCase($page);
    }

    /**
     * Convert page name to display label
     * e.g. "user-management" → "User Management"
     */
    private function toLabel(string $page): string
    {
        if (str_starts_with($page, 'custom:')) {
            $page = substr($page, 7);
        }
        if (str_starts_with($page, 'component:custom:')) {
            $page = substr($page, 17);
        }
        if (str_starts_with($page, 'component:')) {
            $page = substr($page, 10);
        }

        return ucwords(str_replace('-', ' ', $page));
    }

    /**
     * Convert string to kebab-case
     */
    private function toKebabCase(string $str): string
    {
        return strtolower(
            preg_replace('/[A-Z]/', '-$0', lcfirst(
                str_replace([' ', '_'], '-', $str)
            ))
        );
    }

    /**
     * Extract brand/site name from project info.
     * Checks blogName, companyName, storeName, appName in order.
     */
    private function getBrandName(array $projectInfo): string
    {
        return $projectInfo['blogName']
            ?? $projectInfo['companyName']
            ?? $projectInfo['storeName']
            ?? $projectInfo['appName']
            ?? $projectInfo['name']
            ?? 'Template';
    }

    /**
     * Determine file type from file path.
     */
    private function getFileType(string $filePath): string
    {
        $ext = pathinfo($filePath, PATHINFO_EXTENSION);

        return match ($ext) {
            'tsx' => 'tsx',
            'jsx' => 'jsx',
            'vue' => 'vue',
            'svelte' => 'svelte',
            'ts' => 'ts',
            'js' => 'js',
            'css' => 'css',
            'json' => 'json',
            'html' => 'html',
            default => 'config',
        };
    }
}
